routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::group(['as' => 'site.'], function () {
	Route::get('/', 'SiteController@index')->name('index');
	Route::get('/resultados', 'SiteController@resultados')->name('resultado');
	Route::get('/contactar', 'SiteController@contactar')->name('contactar');
	Route::post('/contactar', 'SiteController@contactarSend')->name('contactarSend');
});


/*Route::get('/entrar', 'CompaniesAuth\LoginController@showLoginForm')->name('login');
Route::post('/entrar', 'CompaniesAuth\LoginController@login')->name('login');
Route::post('/sair', 'CompaniesAuth\LoginController@logout')->name('logout');*/

	/*Route::group(['middleware' => 'companyCheckComplementData'], function () {
		Route::get('/painel', 'CompaniesController@home')->name('dashboard');
	});*/

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

	//Route::get('home', 'HomeController@index')->name('home');

	Route::group(['prefix' => 'usuario', 'as' => 'user.'], function () {

		Route::group(['prefix' => 'perfil', 'as' => 'profile.'], function () {

			Route::get('/', 'UserController@show')->name('show');

			Route::get('editar/{id}', 'UserController@edit')->name('edit');
			Route::patch('editar/{id}', 'UserController@update')->name('update');

			Route::group(['middleware' => 'checkIfUserRoleAdmin'], function () {
				Route::get('listar', 'UserController@index')->name('list');
				Route::get('cadastrar', 'UserController@create')->name('create');
				Route::post('cadastrar', 'UserController@store')->name('store');

				/*Route::get('editar/{id}', 'UserController@edit')->name('edit');
				Route::patch('editar/{id}', 'UserController@update')->name('update');*/
			});
		});
	});



    Route::group(['prefix' => 'mensagem', 'as' => 'mensagem.', 'middleware' => 'checkIfUserRoleAdmin'], function () {
        Route::get('/', 'MensagemController@index')->name('index');
        Route::get('/{id}', 'MensagemController@show')->name('show');
    });

	Route::group(['prefix' => 'profissao', 'as' => 'profissao.', 'middleware' => 'checkIfUserRoleAdmin'], function () {
		Route::get('listar', 'ProfissaoController@index')->name('list');
		Route::get('cadastrar', 'ProfissaoController@create')->name('create');
		Route::post('cadastrar', 'ProfissaoController@store')->name('store');
		Route::get('{id}/editar', 'ProfissaoController@edit')->name('edit');
		Route::patch('{id}/editar', 'ProfissaoController@update')->name('update');
		Route::delete('{id}', 'ProfissaoController@delete')->name('delete');
	});

	Route::group(['prefix' => 'unidade', 'as' => 'presidio.', 'middleware' => 'checkIfUserRoleAdmin'], function () {
		Route::get('listar', 'PresidioController@index')->name('list');
		Route::get('cadastrar', 'PresidioController@create')->name('create');
		Route::post('cadastrar', 'PresidioController@store')->name('store');
		Route::get('{id}/editar', 'PresidioController@edit')->name('edit');
		Route::patch('{id}/editar', 'PresidioController@update')->name('update');
		Route::delete('{id}', 'PresidioController@delete')->name('delete');
	});

	Route::group(['prefix' => 'reeducando', 'as' => 'presidiario.'], function () {
		Route::get('listar', 'PresidiarioController@index')->name('list');
		Route::get('cadastrar', 'PresidiarioController@create')->name('create');
		Route::post('cadastrar', 'PresidiarioController@store')->name('store');
		Route::get('{id}', 'PresidiarioController@show')->name('show');
		Route::get('{id}/editar', 'PresidiarioController@edit')->name('edit');
		Route::patch('{id}/editar', 'PresidiarioController@update')->name('update');
		Route::delete('deletar/{id}', 'PresidiarioController@delete')->name('delete');


		Route::group(['prefix' => '{id_preso}/evolucao', 'as' => 'evolucao.'], function () {
			Route::get('cadastrar', 'EvolucaoPresidiarioController@create')->name('create');
			Route::post('cadastrar', 'EvolucaoPresidiarioController@store')->name('store');
		});
	});


    Route::group(['prefix' => 'relatorios', 'as' => 'relatorio.', 'middleware' => 'checkIfUserRoleAdmin'], function () {
        Route::get('/', 'RelatorioController@index')->name('index');
        Route::post('/resultados', 'RelatorioController@results')->name('result');
        Route::get('/resultados', 'RelatorioController@results')->name('result');
    });
    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Presidiario;
use App\Profissao;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;

class SiteController extends Controller
{
	private $presidiario;
	private $profissao;

	public function __construct(Profissao $profissao, Presidiario $presidiario)
	{
		$this->presidiario = $presidiario;
		$this->profissao = $profissao;
	}

	public function index()
    {
    	$profissoes = $this->profissao->all();

        return view('site.index', compact('profissoes'));
    }

	public function resultados()
	{
		#dd(request());

        //$profissoes = $this->profissao->all();

        #$pres_nome = Input::get('reeducando_nome');
        $pres_idade = Input::get('reeducando_idade');
        $pres_sexo = Input::get('reeducando_sexo');
        $pres_profissao = Input::get('reeducando_profissao');
        $pres_regime = Input::get('reeducando_regime');


        #$preso = DB::table('presidiarios')->where('nome', 'LIKE', '%'.$pres_nome.'%');
        #$preso = $this->presidiario->where('nome', 'LIKE', '%'.$pres_nome.'%')->with(['profissao', 'presidio', 'evolucoes']);
        $presos = $this->presidiario/*->where('profissao_id', $pres_profissao)*/->with(['profissao', 'presidio', 'evolucoes']);

        #dd($preso->get());

        if($pres_idade) {
            $now = Carbon::now();

            $age_range = explode('-', $pres_idade);

            $age1 = $now->copy()->subYears($age_range[0]);
            $age2 = $now->copy()->subYears($age_range[1]);

            #dd($age1, $age2, $age_range);

            $presos = $presos->whereBetween('data_nasc', [$age2, $age1]);
            #dd($preso->get());

            /*$preso = $preso->where('data_nasc', '<=',$age2);
            $preso = $preso->where('data_nasc', '>=',$age1);*/
        }

        if($pres_sexo){
            $presos = $presos->where('genero', $pres_sexo);
        }

        if($pres_profissao){
            $presos = $presos->where('profissao_id', $pres_profissao);
        }

        if($pres_regime){
            $presos = $presos->where('regime', $pres_regime);
        }

        $presos = $presos->where('status', true);


		$results = $presos->paginate(2);

        #dd($results);


        return view('site.listagem', compact('results', 'pres_idade', 'pres_sexo', 'pres_profissao'))
            ->with([
                'i' => (request()->input('page', 1) - 1) * 5,
                'reeducando_idade' => $pres_idade,
                'reeducando_sexo' => $pres_sexo,
                'reeducando_profissao' => $pres_profissao
            ]);

    }

    public function contactar()
    {
        return view('site.contactar');
    }

    public function contactarSend()
    {
        #dd(request());

        DB::table('mensagens')->insert([
            'razao_social' => Input::get('contact-razao'),
            'nome_fantasia' => Input::get('contact-nfantasia'),
            'cnpj' => Input::get('contact-cnpj'),
            'segmento' => Input::get('contact-segmento'),
            //'presidiario_id' => Input::get('p_id'),
            //'presidio_id' => Input::get('pres_id'),
            'ano_fundacao' => Input::get('contact-anofundacao'),
            'diretor_responsavel' => Input::get('contact-responsavel'),
            'tel' => Input::get('contact-tel'),
            'email' => Input::get('contact-email'),
            'endereco' => Input::get('contact-endereco'),
            'numero' => Input::get('contact-numero'),
            'bairro' => Input::get('contact-bairro'),
            'observacao' => Input::get('contact-observacao'),
        ]);

        request()->session()->flash('msg-success', ['Mensagem enviada com sucesso, aguarde nosso contato!']);

        return redirect()->route('site.index');
    }

}

resources/views/site/_form-contactar.blade.php
<input type="hidden" name="_token" value="{{ csrf_token() }}">
{{--<input type="hidden" name="p_id" value="{{ $presidiario_id }}">
<input type="hidden" name="pres_id" value="{{ $presidio_id }}">--}}
{{ method_field('POST') }}
<div class="row">
    <div class="large-3 columns">
        <label>Razão Social
            <input type="text" name="contact-razao" placeholder="Razão Social" />
        </label>
    </div>
    <div class="large-3 columns">
        <label>Nome fantasia*
            <input type="text" required name="contact-nfantasia" placeholder="Nome fantasia" />
        </label>
    </div>
    <div class="large-2 columns">
        <label>CNPJ
            <input type="text" name="contact-cnpj" placeholder="CNPJ" />
        </label>
    </div>
    <div class="large-2 columns">
        <label>Segmento*
            {{--<input type="text" required name="contact-segmento" placeholder="Segmento" />--}}
            <select name="contact-segmento" id="">
                <option value="comercio">Comércio</option>
                <option value="industria ">Indústria</option>
                <option value="servicos">Serviços</option>
            </select>
        </label>
    </div>
    <div class="large-2 columns">
        <label>Ano de fundação*
            <input type="text" required name="contact-anofundacao" placeholder="Ano Fundação" />
        </label>
    </div>
</div>
<div class="row">
    <div class="large-6 columns">
        <label>Diretor responsável*
            <input type="text" required name="contact-responsavel" placeholder="" />
        </label>
    </div>
    <div class="large-3 columns">
        <label>Tel*
            <input type="text" required name="contact-tel" placeholder="Nome fantasia" />
        </label>
    </div>
    <div class="large-3 columns">
        <label>E-mail*
            <input type="text" required name="contact-email" placeholder="Nome fantasia" />
        </label>
    </div>
</div>
<div class="row">
    <div class="large-6 columns">
        <label>Endereço*
            <input type="text" required name="contact-endereco" placeholder="Razão Social" />
        </label>
    </div>
    <div class="large-3 columns">
        <label>Número*
            <input type="text" required name="contact-numero" placeholder="Nome fantasia" />
        </label>
    </div>
    <div class="large-3 columns">
        <label>Bairro*
            <input type="text" required name="contact-bairro" placeholder="Nome fantasia" />
        </label>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <label>Observação*
            <textarea name="contact-observacao" placeholder="Utilize esse espaço para descrever o perfil desejado" rows="5" style="resize: none;"></textarea>
        </label>
    </div>
</div>
<div class="row">
    <div class="large-1 columns large-centered">
        <button type="submit" class="button">Enviar</button>
    </div>
</div>
<div class="row">
    <div class="large-9 columns large-centered">
        <p>As mensagens serão enviadas aos servidores do PRORESPE, em breve entraremos em contato </p>
    </div>
</div>

resources/views/site/_form.blade.php
<form action="{{route('site.resultado')}}" method="GET" class="large-12 columns">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="row text-center">
        <h2>Buscar Talento</h2>
    </div>
    {{--<div class="row">
        <div class="large-3 columns large-centered"><br>
            <div class="row">
              <div class="large-10 columns search">
                  <input type="text" name="reeducando_nome" placeholder="Buscar talento"/>
              </div>
              <div class="large-2 columns lupa">
                  <a href="#"><img src="images/site/search.jpg"></a>
              </div>
            </div>
        </div>
    </div> --}}
    <div class="row">
      <div class="large-10 columns large-centered filtro">
        <div class="row">
          <div class="large-3 columns">
            <label>Faixa etária
                <select name="reeducando_idade">
                    <option value="">Selecione</option>
                    <option value="18-25">18-25 Anos</option>
                    <option value="26-30">26-30 Anos</option>
                    <option value="31-35">31-35 Anos</option>
                    <option value="36-40">36-40 Anos</option>
               </select>
            </label>
          </div>
          <div class="large-3 columns">
            <label>Gênero
               <select name="reeducando_sexo">
                   <option value="">Selecione</option>
                   <option value="1" {{ (isset($preso) ? $preso->genero == 1 ? 'selected' : ''  : '' )}}>{{ config('helper.genero.1') }}</option>
                   <option value="2" {{ (isset($preso) ? $preso->genero == 2 ? 'selected' : ''  : '' )}}>{{ config('helper.genero.2') }}</option>
               </select>
            </label>
          </div>
          <div class="large-3 columns">
            <label>Profissão
               <select name="reeducando_profissao">
                   <option value="">Selecione</option>
                   @foreach($profissoes as $pr)
                       <option value="{{$pr->id}}" {{ (isset($preso) ? ( $preso->profissao_id == $pr->id ? 'selected' : 'not' ) : '' ) }}>{{ $pr->nome }}</option>
                   @endforeach
               </select>
            </label>
          </div>
          {{--<div class="large-3 columns">
            <label>Regime
               <select name="reeducando_regime">
                   <option value="">Selecione</option>
                   @foreach(config('helper.regimes') as $k=>$regime)
                       <option value="{{$k}}" {{ ( isset($preso) ? ( $preso->regime == $k ? 'selected' : '' ) : '' )}} >{{ $regime  }}</option>
                   @endforeach
               </select>
            </label>
          </div>--}}
          <div class="large-2 columns large-centered">
            <button type="submit" class="button">Filtrar</button>
          </div>
        </div>
      </div>
    </div>
</form>
<div class="row beneficios">
    <div class="large-10 columns large-centered">
        <center><h2>PRORESPE</h2></center>
        <p>O Programa de Reinserção Social do Sistema Prisional do Estado de Pernambuco tem como objetivo unir esforços Governamentais e  Empresariais com o fim de inserir no mercado de trabalho cidadãos provenientes do sistema prisional. O PRORESPE disponibilizará um banco de atribuições profissionais e supervisões periódicas realizadas por uma equipe multidisciplinar que facilitará a aproximação entre empresas, reeducandos e sociedade. Nos regimes aberto e semi-aberto o reeducando se dirigirá ao local de trabalho externo, no caso do regime fechado, haverá um local adequado, com  segurança, para a empresa desenvolver suas atividades laborais dentro do estabelecimento prisional. O Empresário que desejar contratar o reeducando, após consulta ao sistema, bastará contactar à Secretaria Executiva de Ressocialização. </p>
    </div>
</div>
<hr>

resources/views/site/flash-messages.blade.php
@if(count($errors))
    <div class="form-group">
        <div data-alert class="alert-box alert radius">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
            {{--<a href="#" class="close">&times;</a>--}}
        </div>
    </div>
@endif

@if(session('msg-success'))
    <div class="form-group">
        <div data-alert class="alert-box success radius">
            <ul>
                @foreach(session('msg-success') as $message)
                    <li>{{$message}}</li>
                @endforeach
            </ul>
            {{--<a href="#" class="close">&times;</a>--}}
        </div>
    </div>
@endif

@if(session('msg-infos'))
    <div class="form-group">
        <div class="alert-box warning radius">
            <ul>
                @foreach(session('msg-infos') as $message)
                    <li>{{$message}}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif

{{--<div data-alert class="alert-box success radius">
    This is a success alert with a radius.
    <a href="#" class="close">&times;</a>
</div>--}}

resources/views/site/index.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en" class="no-js" dir="ltr">

@section('head')
    @include('site.site-head')
@show

  <body>
    <div class="fullwight row">
      <img src="images/site/topo.jpg" class="first_img">
        <div class="large columns seres large-centered">
          <center><a href="/"><img src="images/site/seres.png"></a><br><br>
          <span>Programa de Reinserção Social do Sistema Prisional<br>
                    do Estado de Pernambuco</span><br><br>
              <a data-fancybox data-src="#hidden-content" data-fancybox data-width="80%" data-src="#hidden-content" href="javascript:;" class="button">ENTRE EM CONTATO</a>
              <div style="display: none;" id="hidden-content">
                  <h4><center>Contactar Trabalhador</center></h4>
                  <form action="{{route('site.contactar')}}" method="post">
                      @include('site._form-contactar')
                  </form>
              </div>
          </center>
        </div>
    </div>
    <div style="display: none; width: 60%;" id="hidden-content-2">
      <h4><center>Sistema de Reinserção Social do Estado de Pernambuco SIRESPE</center></h4>
<p>O Programa de Reinserção Social do Estado de Pernambuco tem como objetivo unir esforços Governamentais e  Empresariais com o fim de relocar no mercado de trabalho cidadãos apenados. O SIRESPE contará com um banco de atribuições profissionais e  avaliações periódicas que facilitarão a aproximação entre empresas e apenados. Nos regimes aberto e semi-aberto o apenado se dirigirá ao local de trabalho externo, no caso do regime fechado o Empresário fará uma bancada de trabalho no estabelecimento prisional. O Empresário que desejar contratar, após consulta ao sistema, bastará contactar à Secretaria de Ressocialização, no caso de apenados nos regimes fechado e semi-fechado e  Patronato no regime aberto.</p>
    </div>
    <div class="row">
        <div class="conteudo columns large-12">

            <div class="row beneficios">
                <div class="large-10 columns large-centered" style="margin-top: 30px;">
                    @include('site.flash-messages')
                </div>
              @include('site._form')
            </div>
            <div class="row beneficios">
                <div class="row">
                    <div class="large-10 columns large-centered">
                        <div class="large-6 columns">
                            <h2>Benefícios à Sociedade</h2>
                            <p>O ganho econômico e social de mais um cidadão integrante ao mercado de trabalho é positivamente imensurável. Além de  reduzir a probabilidade do apenado  reincidir criminalmente. O trabalho é dever social, dignifica o homem e tem finalidade educativa e produtiva.</p>
                        </div>
                        <div class="large-6 columns">
                            <img src="images/site/sociedade.png">
                        </div>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="large-10 columns large-centered">
                        <div class="large-6 columns">
                            <img src="images/site/empregador.png">
                        </div>
                        <div class="large-6 columns">
                            <h2>Benefícios ao empregador</h2>
                            <p>Conforme o art 28 § 2º,da lei das execuções penais, O trabalho do preso não está sujeito ao regime da Consolidação das Leis do Trabalho, logo o empregador  não arcará com as obrigações sociais. Terá ainda como  vantagem a possibilidade de remunerar o reeducando com o valor de  ¾ do salário mínimo vigente.</p>
                        </div>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="large-10 columns large-centered">
                        <div class="large-6 columns">
                            <h2>Benefícios ao reeducando</h2>
                            <p>No regime fechado e semi-aberto o reeducando poderá ter sua pena reduzida mediante o trabalho regular à razão de um dia a cada três dias trabalhados, segundo a lei das execuções penais, LEI Nº 7.210, DE 11 DE  JULHO DE 1984. O reeducando será remunerado pelas suas atividades laborais.</p>
                        </div>
                        <div class="large-6 columns">
                            <img src="images/site/reeducando.png">
                        </div>
                    </div>
                </div>
            </div>
            <br><br><br>
            <div class="row">
                <div class="large-9 columns large-centered">
                    <center><span><b>Reeducandos dos regimes fechado e semi-aberto</b><br>
                        Secretaria Executiva de Ressocialização - SERES | Gerência de Educação e Qualificação Profissionalizante- GEQP.  Endereço: rua do Hospício, 157, Parque Treze de Maio, Recife-PE.<br>
                        Fone: 3184-2170/99488-s2128.   Email: geqp@seres.pe.gov.br
                      </span></center>
                </div>
            </div>
            <div class="row">
                <div class="large-4 columns large-centered">
                    <br><br><img src="images/site/pe.jpg"><br><br>
                </div>
            </div>
        </div>
    </div>
    @section('scripts')
        @include('site.site-scripts')
    @show
  </body>
</html>

resources/views/site/index_bkp.blade.php
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SIRESPE - Sistema de Reinserção Social do Estado de Pernambuco</title>
    <link rel="stylesheet" href="css/foundation.min.css">
    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" href="css/jquery.fancybox.min.css">

  </head>
  <body>
    <div class="fullwight row">
      <img src="img/topo.jpg" class="first_img">
        <div class="large-8 columns seres large-centered">
          <center><a href="#"><img src="img/seres.png"></a><br><br>
          <span>Sistema de Reinserção Social do<br>
Estado de Pernambuco - SIRESPE</span><br><br>
          <a data-fancybox data-src="#hidden-content-2" href="javascript:;" class="button">SOBRE O PROJETO</a>
          </center>
        </div>
    </div>
    <div style="display: none;" id="hidden-content-2">
      <h4><center>Sistema de Reinserção Social do Estado de Pernambuco SIRESPE</center></h4>
<p>O Programa de Reinserção Social do Estado de Pernambuco tem como objetivo unir esforços Governamentais e  Empresariais com o fim de relocar no mercado de trabalho cidadãos apenados. O SIRESPE contará com um banco de atribuições profissionais e  avaliações periódicas que facilitarão a aproximação entre empresas e apenados. Nos regimes aberto e semi-aberto o apenado se dirigirá ao local de trabalho externo, no caso do regime fechado o Empresário fará uma bancada de trabalho no estabelecimento prisional. O Empresário que desejar contratar, após consulta ao sistema, bastará contactar à Secretaria de Ressocialização, no caso de apenados nos regimes fechado e semi-fechado e  Patronato no regime aberto.</p>
    </div>
    <div class="row">
      <div class="large-12 columns conteudo">
        <div class="row">
            <div class="large-3 columns large-centered"><br>
                <form class="row">
                  <div class="large-10 columns search">
                      <input type="text" placeholder="Buscar talento"/>
                  </div>
                  <div class="large-2 columns lupa">
                      <a href="#"><img src="img/search.jpg"></a>
                  </div>
                </form>
            </div>
        </div>
        <div class="row">
          <div class="large-10 columns large-centered filtro">
            <form class="row">
              <div class="large-3 columns">
                <label>Faixa etária
                   <select>
                      <option value="18-25">18-25 Anos</option>
                      <option value="25-30">25-30 Anos</option>
                      <option value="30-35">30-35 Anos</option>
                      <option value="35-40">35-40 Anos</option>
                   </select> 
                </label>
              </div>
              <div class="large-3 columns">
                <label>Gênero
                   <select>
                      <option value="Masculino">Masculino</option>
                      <option value="Feminino">Feminino</option>
                   </select> 
                </label>
              </div>
              <div class="large-3 columns">
                <label>Profissão
                   <select>
                      <option value="Serviços gerais">Serviços gerais</option>
                      <option value="Secretaria">Secretaria</option>
                      <option value="Vendedora">Vendedora</option>
                      <option value="Cozinheira">Cozinheira</option>
                      <option value="Embaladora">Embaladora</option>
                      <option value="Costureira">Costureira</option>
                      <option value="Auxiliar de cozinha">Auxiliar de cozinha</option>
                      <option value="Técnica de enfermagem">Técnica de enfermagem/option>
                      <option value="Enfermeira">Enfermeira</option>
                      <option value="Camareira">Camareira</option>
                      <option value="Cabeleireira">Cabeleireira</option>
                      <option value="Manicure">Manicure</option>
                      <option value="Caixa de supermercado">Caixa de supermercado</option>
                      <option value="Costureiro de máquina reta e overloque">Costureiro de máquina reta e overloque</option>
                      <option value="Modelista de roupas">Modelista de roupas</option>
                      <option value="Padeiro">Padeiro</option>
                      <option value="Mecânico de máquinas de costura">Mecânico de máquinas de costura</option>
                      <option value="Eletricista de automóveis">Eletricista de automóveis</option>
                      <option value="Eletricista instalador predial de baixa tensão">Eletricista instalador predial de baixa tensão</option>
                      <option value="Pedreiro de alvenaria">Pedreiro de alvenaria</option>
                      <option value="Operador de computador">Operador de computador</option>
                      <option value="Encanador instalador predial">Encanador instalador predial</option>
</option>
                   </select> 
                </label>
              </div>
              <div class="large-3 columns">
                <label>Regime
                   <select>
                      <option value="Fechado">Fechado</option>
                      <option value="Semi-aberto">Semi-aberto</option>
                   </select> 
                </label>
              </div>
              <div class="large-2 columns large-centered">
                <a href="#" class="button">Filtrar</a>
              </div>
            </form>
          </div>
        </div>
        <div class="row beneficios">
          <div class="row">
                <div class="large-10 columns large-centered">
                  <div class="large-6 columns">
                    <h2>Benefícios à Sociedade</h2>
                    <p>O ganho econômico e social de mais um cidadão integrante ao mercado de trabalho é positivamente imensurável. Além de  reduzir a probabilidade do apenado  reincidir criminalmente. O trabalho é dever social, dignifica o homem e tem finalidade educativa e produtiva.</p>
                </div>
                <div class="large-6 columns">
                  <img src="img/apenado.jpg">
                </div>
            </div>
          </div><br><br>
          <div class="row">
              <div class="large-10 columns large-centered">
              <div class="large-6 columns">
                <img src="img/apenado.jpg">
              </div>
              <div class="large-6 columns">
                <h2>Benefícios ao empregador</h2>
                <p>O empregador, no caso do apenado encarcerado, não arcará com obrigações sociais pois não está adstrito a CLT nos termos do art 28 lei das execuções penais.  Terá ainda como vantagem a possibilidade de remunerar inferior ao salário mínimo desde que não seja inferior a ¾ do salário mínimo vigente, conforme art. 29 da lei das execuções.</p>
              </div>
            </div>
          </div><br><br>
          <div class="row">
              <div class="large-10 columns large-centered">
              <div class="large-6 columns">
                  <h2>Benefícios ao apenado</h2>
                  <p>O apenado em regime fechado e semi-aberto poderá ter sua pena reduzida mediante o trabalho regular à razão de um dia a cada três dias trabalhados, segunda a lei das execuções , LEI Nº 7.210, DE 11 DE JULHO DE 1984.</p>
                </div>
              <div class="large-6 columns">
                <img src="img/apenado.jpg">
              </div>              
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-4 columns large-centered">
            <br><br><img src="img/pe.jpg"><br><br>
          </div>
        </div>
      </div>
    </div>
    <script src="js/vendor/jquery.js"></script>
    <script type="text/javascript">
      $(".search input").focus(function() {
          $('.filtro').hide('slow');       
          //return false;
        });      
     $('.search input').blur(function(){
        if( !$(this).val() ) {
              $('.filtro').show('slow');
        }
    });
    </script>
    <script src="js/vendor/what-input.js"></script>
    <script src="js/vendor/foundation.js"></script>
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/vendor/jquery.fancybox.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>